---
title: "For Loops & Purrr"
author: "Shane Jordan"
date: "4/26/2021"
output:
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning=FALSE, 
                      message=FALSE)
```

## Libraries ##
```{r}
library(here)
library(tidyverse)
```

## Create Path to Call Data ##
```{r}
#assign data location
TP1<-read_csv(here("Week_13", "Data", "TP1.csv"))
view(TP1)

#create path
TPpath<-here("Week_13", "Data")

#call files
files <- dir(path = TPpath,pattern = ".csv")
files

#allocate space for summary stats
TPdata<-data.frame(matrix(nrow = length(files), ncol = 5))

#add column names
colnames(TPdata)<-c("filename","mean_temp", "stdev_temp", "mean_light", "stdev_light")
TPdata

#test the first file
raw_data<-read.csv(paste0(TPpath,"/",files[1])) 
head(raw_data)
```

## Make a For Loop w/ summary stats ##
```{r}
for (i in 1:length(files)){ # loop over 1:4 the number of files 
  raw_data<-read_csv(paste0(TPpath,"/",files[i]))
  TPdata$filename[i]<-files[i]
  TPdata$mean_temp[i]<-mean(raw_data$Temp.C, na.rm =TRUE)
  TPdata$mean_light[i]<-mean(raw_data$Intensity.lux, na.rm =TRUE)
  TPdata$stdev_temp[i]<-sd(raw_data$Temp.C, na.rm =TRUE)
  TPdata$stdev_light[i]<-sd(raw_data$Intensity.lux, na.rm =TRUE)
} 
TPdata
```

## Use Purrr to get summary stats##
```{r}
#use purrr
files <- dir(path = TPpath,pattern = ".csv", full.names = TRUE)

#save the entire path name
files

data<-files %>%
  set_names()%>% # set's the id of each list to the file name
  map_df(read_csv,.id = "filename") %>% # map everything to a dataframe and name columns
  group_by(filename) %>%
  summarise(mean_temp = mean(Temp.C, na.rm = TRUE),
            mean_light = mean(Intensity.lux,na.rm = TRUE),
            sd_temp = sd(Temp.C, na.rm = TRUE),
            sd_light = sd(Intensity.lux,na.rm = TRUE))
data
```

