---
title: "Week 12 Lab"
author: "Shane Jordan"
date: "4/21/2021"
output:
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning=FALSE, message=FALSE)
```

## **Working with strings and factors**
## **Load libraries**
```{r}
library(here)
library(tidyverse)
library(janitor)
```
## **Load intertidal data**
```{r}
intertidal_data<-read_csv(here("Week_12","Data","intertidaldata.csv"))
view(intertidal_data)
```
## **Inspect and clean dataset**
```{r}
unique(intertidal_data$Quadrat) #look for any problems in the syntax
#we have "." and "1" that should not be there

#make a new data frame without these mistakes
clean_data <- intertidal_data %>%
  clean_names() %>%
  mutate(quadrat = str_replace_all(quadrat, pattern = "\\.", replacement = " ")) %>% 
  mutate(quadrat = str_replace_all(quadrat, pattern = "[:digit:]|\\:", replacement = "")) %>% 
  mutate(quadrat = str_trim(quadrat, side = "right"))

unique(clean_data$quadrat) #looks better
```
## **Make a ggplot**
```{r, fig.align = "center"}
level_order <- c("Low", "Mid", "High") #order the levels of our factor
clean_data %>%
  ggplot(aes(x = factor(quadrat, level = level_order), y = gooseneck_barnacles))+
  geom_col()+
  facet_wrap(~site)+
  xlab("Tidal Height")+
  ylab("Gooseneck Barnacles (n)")+
  theme_bw()+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  ggsave(here("Week_12", "Output", "Barnacles_Plot.png"), width = 9, height = 9)

```

